# Generated by Django 4.0.5 on 2022-06-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografia', models.ImageField(upload_to='docentes')),
                ('nombre', models.CharField(max_length=50)),
                ('grado_productos', models.CharField(choices=[('Juguete', 'Juguete'), ('Alimento', 'Alimento')], max_length=50)),
            ],
        ),
    ]
