# Generated by Django 4.0.5 on 2022-07-13 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos_a', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='productos_a',
        ),
    ]
