# Generated by Django 4.0.5 on 2022-06-27 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_rename_carrera_dueño_perro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dueño',
            old_name='perro',
            new_name='perros',
        ),
    ]
